ja:
  activerecord:
    models:
      user: ユーザー
      errors:
        messages:
          record_not_found: "%{model}が見つかりません。(model_custom)"
    errors:
      messages:
        record_not_found: "%{model}が見つかりません。(default)"
